### ISSUE TITLE
Does cpbooster support brave for submitting problems?? (also, some NodeJs installation issues)

### ISSUE THREAD

**Issue by MohamedIrfanAM** [searleser97/cpbooster.vim#1]
I have'nt installed chromium.
I tried to `cpb login codeforces`, it is giving me following errors
```
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

browserType.launch: Failed to launch chromium because executable doesn't exist at /home/irfan/.cache/ms-playwright/chromium-857950/chrome-linux/chrome
Try re-installing playwright with "npm install playwright"
Error
    at Object.captureStackTrace (/usr/lib/node_modules/cpbooster/node_modules/playwright-chromium/lib/utils/stackTrace.js:48:19)
    at Connection.sendMessageToServer (/usr/lib/node_modules/cpbooster/node_modules/playwright-chromium/lib/client/connection.js:69:48)
    at Proxy.<anonymous> (/usr/lib/node_modules/cpbooster/node_modules/playwright-chromium/lib/client/channelOwner.js:64:61)
    at /usr/lib/node_modules/cpbooster/node_modules/playwright-chromium/lib/client/browserType.js:64:67
    at BrowserType._wrapApiCall (/usr/lib/node_modules/cpbooster/node_modules/playwright-chromium/lib/client/channelOwner.js:77:34)
    at BrowserType.launch (/usr/lib/node_modules/cpbooster/node_modules/playwright-chromium/lib/client/browserType.js:55:21)
    at Codeforces.<anonymous> (/usr/lib/node_modules/cpbooster/dist/Submit/OnlineJudgeFactory/OnlineJudge.js:224:81)
    at step (/usr/lib/node_modules/cpbooster/dist/Submit/OnlineJudgeFactory/OnlineJudge.js:69:23)
    at Object.next (/usr/lib/node_modules/cpbooster/dist/Submit/OnlineJudgeFactory/OnlineJudge.js:50:53)
    at /usr/lib/node_modules/cpbooster/dist/Submit/OnlineJudgeFactory/OnlineJudge.js:44:71

```

No problem if it doesn't support 😃 Thank you so much , this extension saved me a lot of time

**Comment by searleser97** [comment]
interesting catch here, `cpbooster` uses `playwright` for web scrapping, therefore `chromium` binaries should be installed automatically based on what they say here: https://playwright.dev/docs/intro/ and here: https://playwright.dev/docs/installation/

Could you tell me if everything works as expected if you run the following command?

```shell
npm i -D playwright
```

Probably you erased your `cache` recently?

**Comment by searleser97** [comment]
Could you also check if reinstalling `cpbooster` helps?
```
npm uninstall cpbooster -g
```
and then
```
npm install cpbooster -g
```

Note: I just installed `cpbooster` in a new Ubuntu machine (without chromium), and it worked perfectly out of the box. There was no need to install chromium manually, the binaries are located in `/home/$USER/.cache/ms-playwright` as the documentation from `playwright` says.

**Comment by MohamedIrfanAM** [comment]
Installing chromium manually didn't help 
I tried installing playwright with `sudo npm i -D playwright`, but its giving me some errors
I ran this command as a super user ` sudo su`
```
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/cpbooster
npm ERR! dest /usr/lib/node_modules/.cpbooster-VBQkHeHX
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/cpbooster' -> '/usr/lib/node_modules/.cpbooster-VBQkHeHX'
npm ERR!  [Error: EACCES: permission denied, rename '/usr/lib/node_modules/cpbooster' -> '/usr/lib/node_modules/.cpbooster-VBQkHeHX'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/usr/lib/node_modules/cpbooster',
npm ERR!   dest: '/usr/lib/node_modules/.cpbooster-VBQkHeHX'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/irfan/.npm/_logs/2021-04-15T16_05_34_049Z-debug.log

```

I have a _.links_ file in `~/.cache/ms-playwright/`

I have reinstalled cpbooster, still not working 😞

**Comment by MohamedIrfanAM** [comment]
Any way to install playwright other than npm ??

**Comment by searleser97** [comment]
could you try installing `node` / `npm` with `nvm` ? I think your issue is related with the need of using `sudo` to install packages. 
when you use `sudo` your `$USER` is `root` instead of `irfan` so probably the binaries are getting installed in `/root/.cache/ms-playwrigth/...` or some other location or even not being able to install them due to the lack of write permissions.

steps to install `node` and `npm` with `nvm`:

- first be sure that you have uninstalled `cpbooster` from your current node installation. You can just run `npm uninstall cpbooster -g`.

1. `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash`
2. open a **new** terminal and run `nvm install node`
3. `nvm use node`
4. install `cpbooster` with `npm install cpbooster -g` (without `sudo`)

hope this helps

**Comment by MohamedIrfanAM** [comment]
`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash`
```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14926  100 14926    0     0  35369      0 --:--:-- --:--:-- --:--:-- 35286
=> nvm is already installed in /home/irfan/.nvm, trying to update using git
=> => Compressing and cleaning up git repository

=> nvm source string already in /home/irfan/.bashrc
=> bash_completion source string already in /home/irfan/.bashrc
=> You currently have modules installed globally with `npm`. These will no
=> longer be linked to the active version of Node when you install a new node
=> with `nvm`; and they may (depending on how you construct your `$PATH`)
=> override the binaries of modules installed with `nvm`:

/usr/lib
├── neovim@4.9.0
├── node-gyp@7.1.2
├── semver@7.3.5
└── yarn@1.22.10
=> If you wish to uninstall them at a later point (or re-install them under your
=> `nvm` Nodes), you can remove them from the system Node as follows:

     $ nvm use system
     $ npm uninstall -g a_module

=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

```

It says nvm is already installed but when i run _nvm install node_ it says command not found

**Comment by searleser97** [comment]
did you close and open a **new** terminal ?

**Comment by MohamedIrfanAM** [comment]
Sorry for late reply, yesterday my wifi connection got lost ( I am from India)
I wasn't using using bash, that why nvm wasn't working
After following these steps 

> first be sure that you have uninstalled cpbooster from your current node installation. You can just run npm uninstall cpbooster -g.
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
open a new terminal and run nvm install node
nvm use node
install cpbooster with npm install cpbooster -g (without sudo)

I got it working in chromium. Can I get it working in brave ??

**Comment by searleser97** [comment]
Currently, the only supported browser is `chromium` as provided by `playwright`. However, you could send a Pull Request with this optional feature since `brave` is chromium-based. Probably you would need to add some optional fields in `cpbooster-config.json` and modify some code here: https://github.com/searleser97/cpbooster/blob/19808863db7a2c9c22967a51897871b03f970d7b/src/Submit/OnlineJudgeFactory/OnlineJudge.ts#L122

**Comment by MohamedIrfanAM** [comment]
Thank you for your time 😄, I will use Chromium from now onwards, because this feature is very useful
