### ISSUE TITLE
Open tabs/buffers when adding new testcase

### ISSUE THREAD

**Issue by PieroNarciso** [searleser97/cpbooster.vim#2]
When using `:Addtc` I think it should be more comfortable editing the input and expected output in vim mode
So, maybe when using the command, the plugin should create two new buffers
For example in `B.problemname.cpp`
Opens:
* `B.problemname.in2`
* `B.problemname.ans2`
and edit them with vim/neovim, then just save the two buffers.

**Comment by searleser97** [comment]
Happy to share that your request has been satisfied :), please update to see the new behavior

![image](https://user-images.githubusercontent.com/5056411/127545616-dbb9a605-c4ab-408e-9cb7-9a488c11b064.png)

**Comment by PieroNarciso** [comment]
Thanks, I just updated to the new version
