### ISSUE TITLE
Use :up instead of :w?

### ISSUE THREAD

**Issue by user202729** [searleser97/cpbooster.vim#4]
There are many instances in the code where `:w` is used.

It may be better to change it to `:up` so another write is unnecessary (unless you explicitly want to show the status line.)

**Comment by searleser97** [comment]
sounds good, It'll be awesome if you could submit a PR with this change :)

**Comment by user202729** [comment]
I'll after the existing pull request is handled, because it conflicts.

**Comment by searleser97** [comment]
already merged your previous PR :)
